"""UUIDv7 identifiers required by the database key constraints (`14` §2)."""

from __future__ import annotations

import os
import time
from uuid import UUID

UUID7_VERSION_NIBBLE = 0x70
UUID7_VARIANT_BITS = 0x80


def uuid7(*, timestamp_ms: int | None = None) -> UUID:
    """Return a time-ordered UUIDv7 that satisfies the pls_is_uuid_v7 check.

    Append-only tables key on UUIDv7 so that primary keys stay monotonic in time.
    The database rejects any other version, so identifiers are never generated by
    uuid4 or by the client at random.
    """
    moment = time.time_ns() // 1_000_000 if timestamp_ms is None else timestamp_ms
    if moment < 0:
        raise ValueError("timestamp_ms must not be negative")
    payload = bytearray(moment.to_bytes(6, "big") + os.urandom(10))
    payload[6] = (payload[6] & 0x0F) | UUID7_VERSION_NIBBLE
    payload[8] = (payload[8] & 0x3F) | UUID7_VARIANT_BITS
    return UUID(bytes=bytes(payload))


def is_uuid7(value: UUID) -> bool:
    """Mirror the database predicate so callers can assert before a write."""
    raw = value.bytes
    return (raw[6] >> 4) == 7 and (raw[8] >> 6) == 2
